"""add_column_fwd_to_users_table

Revision ID: b05cd437b16b
Revises: ea22811b1f04
Create Date: 2022-02-04 18:21:52.499640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05cd437b16b'
down_revision = 'ea22811b1f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fwd', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fwd')
    # ### end Alembic commands ###
