name: Linter Runner

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install pylint
        run: pip install pylint

      - name: Install mypy
        run: pip install git+https://github.com/python/mypy.git@40bbfb5f2539f6fc3ea8c9b4de6b62d167bb003f

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pylint
        run: find -name "*.py" -not -path "./.git/*" -not -path "*/alembic/versions/*" -not -path "*/tests/*" | xargs pylint --rcfile=.pylintrc
      - name: Run mypy
        run: mypy --exclude=tests/ --exclude=apps/ .
      - name: Run tests
        env:
          ROCKET_CHAT_API: http://localhost:8006/api/v1
          USER_NAME: meeseeks
          PASSWORD: testpassword
          PG_NAME: happy_birthder_base
          PG_HOST: localhost
          PG_PORT: 5432
          PG_USER: postgres
          PG_PASSWORD: testpassword
        run: env PYTHONPATH=$(pwd) python3 tests/run_tests.py
