name: Linter Runner

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install pylint
        run: pip install pylint

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pylint
        run: |
             find -name "*.py" -not -path "./.git/*" -not -path "*/alembic/versions/*" | xargs pylint --rcfile=.pylintrc
